fix(ci): move to bundlemon v3 (#2330)
* fix: include ng19 integration test everywhere

* fix: use github action for bundlemon

* chore(ci): upgrade to bundlemon v3.1.0

* chore(ci): regenerate yarn.lock file

* chore(ci): regenerate yarn.lock file again

* chore(integration): fix build issue with integration app

The error resolved was:
Error: node_modules/parse5/dist/tokenizer/index.d.ts:3:31 - error TS7016: Could not find a declaration file for module 'entities/decode'. 'C:/dev/personal/ngxs/node_modules/parse5/node_modules/entities/decode.js' implicitly has an 'any' type.
        Try `npm i --save-dev @types/entities` if it exists or add a new declaration (.d.ts) file containing `declare module 'entities/decode';`
      3 import { EntityDecoder } from 'entities/decode';

* chore(ci): update bundlemon limits

* chore(ci): test out an explicit bundlemon project id

* Revert "chore(ci): test out an explicit bundlemon project id"

This reverts commit 240b014d16263b92b8f680e13ea618ab4ec50365.

* chore(ci): bundlemon steps should not fail on error

* chore: update CHANGELOG.md